#!/usr/bin/env bash
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function print_password() {
	local password="$1"
	echo
	# print the entered password on stdout (surrounded by quotes)
	echo "Password: \"${password}\""
	# print the entered password on stdout (converted to hexadecimal)
	echo "Password in hex:" $(echo -n "${password}"|xxd -p -c 256)
}

# loading the read_hidden library
source $dir/read_hidden

# print the help of the command
read_hidden -h

# use read_hidden with default options and provide an hard-coded password on stdin
# the provided password will be like the user has typed
# "test passworD[backspace]d" (quotes excluded)
read_hidden mypassword << HEREDOC
test passworD$(echo $'\x7f')d
HEREDOC
print_password "$mypassword"

# use read_hidden with custom prompt and echo sequence and wait for the user to
# enter a password manually
read_hidden -p "Now write your password manually here: " -e "[]" mypassword
print_password "$mypassword"

exit 0
